package me.himashusoni.thermalprinter.core;

public class AsciiByte {

    public static final byte NUL = 0x00;
    public static final byte SOH = 0x01;
    public static final byte STX = 0x02;
    public static final byte ETX = 0x03;
    public static final byte EOT = 0x04;
    public static final byte ENQ = 0x05;
    public static final byte ACK = 0x06;
    public static final byte BEL = 0x07;
    public static final byte BS = 0x08;
    public static final byte HT = 0x09;
    public static final byte LF = 0x0A;
    public static final byte VT = 0x0B;
    public static final byte FF = 0x0C;
    public static final byte CR = 0x0D;
    public static final byte SO = 0x0E;
    public static final byte SI = 0x0F;
    public static final byte DLE = 0x10;
    public static final byte DC1 = 0x11;
    public static final byte DC2 = 0x12;
    public static final byte DC3 = 0x13;
    public static final byte DC4 = 0x14;
    public static final byte NAK = 0x15;
    public static final byte SYN = 0x16;
    public static final byte ETB = 0x17;
    public static final byte CAN = 0x18;
    public static final byte EM = 0x19;
    public static final byte SUB = 0x1A;
    public static final byte ESC = 0x1B;
    public static final byte FS = 0x1C;
    public static final byte GS = 0x1D;
    public static final byte RS = 0x1E;
    public static final byte US = 0x1F;
    public static final byte SPACE = 0x20;

    public static final byte EXCLAMATION_MARK = 0x21; // !
    public static final byte QUOTATION_MARK = 0x22; // "
    public static final byte NUMBER_SIGN = 0x23; // #
    public static final byte DOLLAR_SIGN = 0x24; // $
    public static final byte PERCENT_SIGN = 0x25; // %
    public static final byte AMPERSAND = 0x26; // &
    public static final byte SINGLE_QUOTE = 0x27; // '
    public static final byte LEFT_PARENTHESIS = 0x28; // (
    public static final byte RIGHT_PARENTHESIS = 0x29; // )
    public static final byte ASTERISK = 0x2A; // *
    public static final byte PLUS_SIGN = 0x2B; // +
    public static final byte COMMA = 0x2C; // ,
    public static final byte HYPHEN = 0x2D; // -
    public static final byte PERIOD = 0x2E; // .
    public static final byte SLASH = 0x2F; // /
    public static final byte DIGIT_0 = 0x30;
    public static final byte DIGIT_1 = 0x31;
    public static final byte DIGIT_2 = 0x32;
    public static final byte DIGIT_3 = 0x33;
    public static final byte DIGIT_4 = 0x34;
    public static final byte DIGIT_5 = 0x35;
    public static final byte DIGIT_6 = 0x36;
    public static final byte DIGIT_7 = 0x37;
    public static final byte DIGIT_8 = 0x38;
    public static final byte DIGIT_9 = 0x39;
    public static final byte COLON = 0x3A; // :
    public static final byte SEMICOLON = 0x3B; // ;
    public static final byte LESS_THAN = 0x3C; // <
    public static final byte EQUALS = 0x3D; // =
    public static final byte GREATER_THAN = 0x3E; // >
    public static final byte QUESTION_MARK = 0x3F; // ?
    public static final byte COMMERCIAL_AT = 0x40; // @
    public static final byte UPPERCASE_A = 0x41; // A
    public static final byte UPPERCASE_B = 0x42; //
    public static final byte UPPERCASE_C = 0x43; //
    public static final byte UPPERCASE_D = 0x44; //
    public static final byte UPPERCASE_E = 0x45; //
    public static final byte UPPERCASE_F = 0x46; //
    public static final byte UPPERCASE_G = 0x47; //
    public static final byte UPPERCASE_H = 0x48; //
    public static final byte UPPERCASE_I = 0x49; //
    public static final byte UPPERCASE_J = 0x4A; //
    public static final byte UPPERCASE_K = 0x4B; //
    public static final byte UPPERCASE_L = 0x4C; //
    public static final byte UPPERCASE_M = 0x4D; //
    public static final byte UPPERCASE_N = 0x4E; //
    public static final byte UPPERCASE_O = 0x4F; //
    public static final byte UPPERCASE_P = 0x50; //
    public static final byte UPPERCASE_Q = 0x51; //
    public static final byte UPPERCASE_R = 0x52; //
    public static final byte UPPERCASE_S = 0x53; //
    public static final byte UPPERCASE_T = 0x54; //
    public static final byte UPPERCASE_U = 0x55; //
    public static final byte UPPERCASE_V = 0x56; //
    public static final byte UPPERCASE_W = 0x57; //
    public static final byte UPPERCASE_X = 0x58; //
    public static final byte UPPERCASE_Y = 0x59; //
    public static final byte UPPERCASE_Z = 0x5A; // Z
    public static final byte LEFT_BRACKET = 0x5B; // [
    public static final byte REVERSE_SLANT = 0x5C; // \
    public static final byte RIGHT_BRACKET = 0x5D; // ]
    public static final byte CIRCUMFLEX_ACCENT = 0x5E; // ^
    public static final byte UNDERSCORE = 0x5F; // _
    public static final byte GRAVE_ACCENT = 0x60; // `
    public static final byte LOWERCASE_A = 0x61; // a
    public static final byte LOWERCASE_B = 0x62; //
    public static final byte LOWERCASE_C = 0x63; //
    public static final byte LOWERCASE_D = 0x64; //
    public static final byte LOWERCASE_E = 0x65; //
    public static final byte LOWERCASE_F = 0x66; //
    public static final byte LOWERCASE_G = 0x67; //
    public static final byte LOWERCASE_H = 0x68; //
    public static final byte LOWERCASE_I = 0x69; //
    public static final byte LOWERCASE_J = 0x6A; //
    public static final byte LOWERCASE_K = 0x6B; //
    public static final byte LOWERCASE_L = 0x6C; //
    public static final byte LOWERCASE_M = 0x6D; //
    public static final byte LOWERCASE_N = 0x6E; //
    public static final byte LOWERCASE_O = 0x6F; //
    public static final byte LOWERCASE_P = 0x70; //
    public static final byte LOWERCASE_Q = 0x71; //
    public static final byte LOWERCASE_R = 0x72; //
    public static final byte LOWERCASE_S = 0x73; //
    public static final byte LOWERCASE_T = 0x74; //
    public static final byte LOWERCASE_U = 0x75; //
    public static final byte LOWERCASE_V = 0x76; //
    public static final byte LOWERCASE_W = 0x77; //
    public static final byte LOWERCASE_X = 0x78; //
    public static final byte LOWERCASE_Y = 0x79; //
    public static final byte LOWERCASE_Z = 0x7A; // z
    public static final byte LEFT_BRACE = 0x7B; // {
    public static final byte VERTICAL_BAR = 0x7C; // |
    public static final byte RIGHT_BRACE = 0x7D; // }
    public static final byte TILDE = 0x7D; // ~
    public static final byte DEL = 0x7F;

    public static final byte EOF = -1;
}
